server:
  port: 8080
spring:
  #  mvc:
  #    view:
  #      prefix: /
  #      suffix: .html
#  mvc:
#    static-path-pattern: /static/**
  thymeleaf:
#    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    enabled: true
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://192.168.0.105:3306/demo?serverTimezone=GMT%2B8
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
#  resources:
#    static-locations: classpath:/static/